/*
 * Copyright © 2019 Intel Corporation
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

#include "ibc_ra_reg_sets.h"

#include "util/blob.h"

#include <stdio.h>

int main(int arc, char **argv)
{
   FILE *fp = fopen(argv[1], "w");
   if (fp == NULL)
      abort();

   fprintf(fp, "/* This file is autogenerated by ibc_build_ra_reg_sets.c. "
               "DO NOT EDIT! */\n");

   for (unsigned simd_width = 8; simd_width <= 32; simd_width *= 2) {
      void *mem_ctx = ralloc_context(NULL);

      ibc_ra_reg_set set;
      ibc_ra_reg_set_init(&set, simd_width, mem_ctx);

      struct blob blob;
      blob_init(&blob);

      ra_set_serialize(set.regs, &blob);

      fprintf(fp, "\n");
      fprintf(fp, "static const uint32_t ibc_ra_reg_set_simd%u[] = {\n",
              simd_width);

      assert(blob.size % sizeof(uint32_t) == 0);
      size_t num_u32s = blob.size / sizeof(uint32_t);
      uint32_t *data_u32 = (uint32_t *)blob.data;
      for (size_t i = 0; i < num_u32s; i++) {
         if (i % 6 == 0)
            fprintf(fp, "  ");
         fprintf(fp, " 0x%08x,", data_u32[i]);
         if (i % 6 == 5)
            fprintf(fp, "\n");
      }

      fprintf(fp, "};\n");

      blob_finish(&blob);
      ralloc_free(mem_ctx);
   }

   fclose(fp);

   return 0;
}
